// Los 31 estados de México EXCLUYENDO Querétaro — ese caso ya lo cubre el
// flujo 2 (envío local), que asume Querétaro sin pedirlo como campo. Solo
// se usa en el dropdown de Estado del flujo 3 (envío foráneo).
export const MEXICAN_STATES_EXCLUDING_QUERETARO = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "México",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
] as const;
